app:
  name: 'test app'
  api_name: 'test nest'
  desc: 'This is a test nest app'
  version: '1.0.0'
  port: 3002

database:
  dialect: 'mysql'
  name: 'primary_db'
  host: 'localhost'
  port: 33061
  username: 'root'
  password: ''
  database: 'test'
  autoLoadModels: true
  synchronize: true # true for all except prod
